
substitutions:
  device: watering1
  sleep_duration: 1min
  run_duration: 1min
  update_interval_moisture  : 60 min
  expire_after_moisture : 60 min 
       
esphome:
  name: $device
  friendly_name: Benno_$device

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: NONE #ERROR  NONE DEBUG

# Enable Home Assistant API
#api:
#  encryption:
#    key: "b1OonrUr1YaxOf5Wz0FR3n3oGJCcH1Vb8Cab7+5hCgQ="

ota:
  password: "ca6cddb3e967b0bddc1d9ac655f86969"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bennoesp32 Fallback Hotspot"
    password: "1BSeHqsrQnQi"

mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_user
  password: !secret mqtt_password
  port: !secret mqtt_port
  skip_cert_cn_check: false
  idf_send_async: false
  
  on_message:
    - topic: $device/ota_mode
      qos: 0                                          #1
      payload: 'on'
      then:
        - logger.log:
            format: 'MQTT Admin: disable deep sleep'
            level: ERROR
#        - deep_sleep.prevent: deep_sleep_control
    - topic: $device/sleep_mode
      qos: 0                                          #1
      payload: 'off'
      then:
        - logger.log:
            format: 'MQTT Admin: entering deep sleep'
            level: ERROR
 #       - deep_sleep.enter: deep_sleep_control


  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----


deep_sleep:
  id: deep_sleep_control
  run_duration: $run_duration
  sleep_duration: $sleep_duration

time:
  - platform: sntp
    id: sntp_time

sensor:
  # Example configuration entry with 2 sensors and filter
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 3600s
    entity_category: "diagnostic"
#    state_topic: $device/wifi_signal_db

  - platform: adc
    pin: GPIO32
    name: "Soil Moisture 1"
    unit_of_measurement: "%"
    id: soil_moisture1   
    update_interval: $update_interval_moisture
    state_topic: $device/soil_moisture1
    attenuation: 11db
    retain: true
    expire_after: $expire_after_moisture
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.98 -> 100.00
        - 1.8 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0    

  - platform: adc
    pin: GPIO33
    name: "Soil Moisture 2"
    update_interval: $update_interval_moisture
#    update_interval: 6s
    unit_of_measurement: "%"
    id: soil_moisture2   
    state_topic: $device/soil_moisture2
    attenuation: 11db
    retain: true
#    expire_after: 10 minutes
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.98 -> 100.00
        - 1.8 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0   

  - platform: adc
    pin: GPIO34
    name: "Soil Moisture 3"
    update_interval: $update_interval_moisture
    unit_of_measurement: "%"
    id: soil_moisture3   
    state_topic: $device/soil_moisture3
    attenuation: 11db
    retain: true
 #   expire_after: 10 minutes
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.98 -> 100.00
        - 1.8 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0   

  - platform: adc
    pin: GPIO35
    name: "Soil Moisture 4"
    update_interval: $update_interval_moisture
    unit_of_measurement: "%"
    id: soil_moisture4   
    state_topic: $device/soil_moisture4
    attenuation: 11db
    retain: true
 #   expire_after: 10 minutes
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 1.5 -> 100.00
        - 1.8 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0   

  - platform: mqtt_subscribe
    id: waterpump_time1
    topic:  $device/waterpump1
    on_value:
      then:
        - logger.log: "waterpump 1"
        - switch.turn_on: waterpump1
        - delay: !lambda "return  id(waterpump_time1).state * 1000 ;"
        - switch.turn_off: waterpump1
        - delay: 2s 
#        - deep_sleep.enter: 
#            sleep_duration: 1min


switch:
  - platform: gpio
    name: "Waterpump 1"
    id: waterpump1   
    pin: GPIO22
#    retain: true
    state_topic: $device/waterpump_state_1

      



 
 

  